basePath: /
definitions:
  models.CreateTodos:
    properties:
      completed:
        type: boolean
      title:
        type: string
    type: object
  models.Todos:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Berikut ini adalah final project 1 mengenai pembuatan TODOLIST berbasis
    API.
  title: Final Project 1 Hacktiv8 TODOS
paths:
  /todos:
    get:
      description: Get a list of todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todos'
            type: array
      summary: Get all todos
    post:
      consumes:
      - application/json
      description: Create a new todos
      parameters:
      - description: Todo input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateTodos'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todos'
      summary: Create a todos
  /todos/{id}:
    delete:
      description: Delete a todos by ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todos'
      summary: Delete a todos by ID
    get:
      description: Get a todo by ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todos'
      summary: Get a todos by ID
    put:
      consumes:
      - application/json
      description: Update a todos by ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      - description: Todo input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateTodos'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todos'
      summary: Update a todos by ID
swagger: "2.0"
